apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: argocd
spec:
  project: argocd-ui
  source:
    repoURL: https://github.com/anilshakya23/azure-terraform-app-infra.git
    targetRevision: main
    path: .
    ref: menifest
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-ui